# Generated by Django 5.2.12 on 2026-04-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_galleryimage_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_key',
        ),
        migrations.RemoveField(
            model_name='managementmember',
            name='image_key',
        ),
    ]
