# Generated by Django 5.2.12 on 2026-04-05 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_galleryimage_image_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=200)),
                ('form_range', models.CharField(blank=True, max_length=100)),
                ('roll_range', models.CharField(blank=True, max_length=100)),
                ('extra_details', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSamplePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='exam/sample-papers/')),
                ('external_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSupportSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('principal_name', models.CharField(blank=True, max_length=200)),
                ('principal_image', models.ImageField(blank=True, null=True, upload_to='exam/support-schools/')),
                ('contact_info', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSyllabusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='exam/syllabus/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='examregistration',
            name='admit_card_file',
            field=models.FileField(blank=True, null=True, upload_to='exam/admit-cards/'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='participation_certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='exam/certificates/'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='publish_admit_card',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='publish_participation_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='exam/signatures/'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='student_image',
            field=models.ImageField(blank=True, null=True, upload_to='exam/students/'),
        ),
        migrations.CreateModel(
            name='ExamTopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=1)),
                ('highlight_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topper_entries', to='api.examregistration')),
            ],
            options={
                'ordering': ['order', 'rank', 'id'],
            },
        ),
    ]
