# Generated by Django 5.2.12 on 2026-04-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_examcenterdetail_examfaq_examimportantdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_closed', models.BooleanField(default=False, help_text='When enabled, new exam registrations will be rejected.')),
            ],
            options={
                'verbose_name': 'Exam Settings',
                'verbose_name_plural': 'Exam Settings',
            },
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
