# Generated by Django 5.2.12 on 2026-04-11 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_examregistration_examination_center_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='complaints/screenshots/')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.examregistration')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
    ]
