# Generated by Django 5.2.12 on 2026-04-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_reconcile_teamregistration_payment_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
