# Generated by Django 5.2.12 on 2026-04-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_teamregistration_is_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamregistration',
            old_name='village_name',
            new_name='address',
        ),
    ]
