# Generated by Django 5.2.12 on 2026-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_village_name_teamregistration_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='team_image',
            field=models.ImageField(blank=True, null=True, upload_to='team-registrations/team-images/'),
        ),
    ]
