# Generated by Django 5.2.12 on 2026-05-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_newsticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('heading_hi', models.CharField(blank=True, help_text='Hindi translation of heading', max_length=200)),
                ('description', models.TextField()),
                ('description_hi', models.TextField(blank=True, help_text='Hindi translation of description')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community/highlights/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Ceremony', 'Ceremony'), ('Team', 'Team'), ('Community', 'Community'), ('Exam', 'Exam')], max_length=50),
        ),
    ]
