# Generated by Django 5.2.12 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_community_highlight_and_gallery_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball_number', models.PositiveSmallIntegerField()),
                ('runs_off_bat', models.PositiveSmallIntegerField(default=0)),
                ('is_extra', models.BooleanField(default=False)),
                ('extra_type', models.CharField(blank=True, choices=[('wide', 'Wide'), ('no_ball', 'No Ball'), ('bye', 'Bye'), ('leg_bye', 'Leg Bye'), ('penalty', 'Penalty')], max_length=20)),
                ('extra_runs', models.PositiveSmallIntegerField(default=0)),
                ('is_wicket', models.BooleanField(default=False)),
                ('wicket_type', models.CharField(blank=True, choices=[('bowled', 'Bowled'), ('caught', 'Caught'), ('lbw', 'LBW'), ('run_out', 'Run Out'), ('stumped', 'Stumped'), ('hit_wicket', 'Hit Wicket'), ('retired_hurt', 'Retired Hurt'), ('obstructing_field', 'Obstructing Field')], max_length=30)),
                ('is_boundary', models.BooleanField(default=False)),
                ('is_six', models.BooleanField(default=False)),
                ('commentary', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['over', 'ball_number'],
            },
        ),
        migrations.CreateModel(
            name='BatsmanScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs', models.PositiveIntegerField(default=0)),
                ('balls_faced', models.PositiveSmallIntegerField(default=0)),
                ('fours', models.PositiveSmallIntegerField(default=0)),
                ('sixes', models.PositiveSmallIntegerField(default=0)),
                ('is_out', models.BooleanField(default=False)),
                ('dismissal_type', models.CharField(blank=True, max_length=30)),
                ('is_batting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BowlerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overs', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('maidens', models.PositiveSmallIntegerField(default=0)),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('wides', models.PositiveSmallIntegerField(default=0)),
                ('no_balls', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Innings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings_number', models.PositiveSmallIntegerField()),
                ('batting_team_name', models.CharField(max_length=200)),
                ('bowling_team_name', models.CharField(max_length=200)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('overs_completed', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('extras', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('target', models.PositiveIntegerField(blank=True, null=True)),
                ('batting_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batting_innings', to='api.teamregistration')),
                ('bowling_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bowling_innings', to='api.teamregistration')),
            ],
            options={
                'ordering': ['match', 'innings_number'],
            },
        ),
        migrations.CreateModel(
            name='Over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_number', models.PositiveSmallIntegerField()),
                ('runs', models.PositiveSmallIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('extras', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['innings', 'over_number'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('batter', 'Batter'), ('bowler', 'Bowler'), ('allrounder', 'All-rounder'), ('wicketkeeper', 'Wicket-keeper')], default='batter', max_length=20)),
                ('batting_style', models.CharField(choices=[('right_handed', 'Right-handed'), ('left_handed', 'Left-handed')], default='right_handed', max_length=30)),
                ('bowling_style', models.CharField(choices=[('right_arm_fast', 'Right-arm Fast'), ('right_arm_medium', 'Right-arm Medium'), ('right_arm_off_spin', 'Right-arm Off Spin'), ('right_arm_leg_spin', 'Right-arm Leg Spin'), ('left_arm_fast', 'Left-arm Fast'), ('left_arm_medium', 'Left-arm Medium'), ('left_arm_spin', 'Left-arm Spin'), ('not_applicable', 'N/A')], default='not_applicable', max_length=30)),
                ('jersey_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_captain', models.BooleanField(default=False)),
                ('is_substitute', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cricket/players/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.teamregistration')),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.IntegerField(choices=[(2025, 'HBPL 2025'), (2026, 'HBPL 2026')])),
                ('format', models.CharField(choices=[('knockout', 'Knockout'), ('league', 'League'), ('group_knockout', 'Group Stage + Knockout')], default='knockout', max_length=20)),
                ('max_teams', models.PositiveSmallIntegerField(default=16)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='upcoming', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('registration_fee_paise', models.PositiveIntegerField(default=0)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='cricket/tournaments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-season', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_order_id', models.CharField(blank=True, max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payment_signature', models.CharField(blank=True, max_length=255)),
                ('payment_amount_paise', models.PositiveIntegerField(default=0)),
                ('admin_note', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='api.teamregistration')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='api.tournament')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.DeleteModel(
            name='CommunityHighlight',
        ),
        migrations.AddField(
            model_name='match',
            name='match_status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_matches', to='api.teamregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_matches', to='api.teamregistration'),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_decision',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='match',
            name='toss_winner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Ceremony', 'Ceremony'), ('Team', 'Team')], max_length=50),
        ),
        migrations.AddField(
            model_name='innings',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='innings', to='api.match'),
        ),
        migrations.AddField(
            model_name='bowlerscore',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_scores', to='api.innings'),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsman_scores', to='api.innings'),
        ),
        migrations.AddField(
            model_name='over',
            name='innings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overs', to='api.innings'),
        ),
        migrations.AddField(
            model_name='ball',
            name='over',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balls', to='api.over'),
        ),
        migrations.AddField(
            model_name='over',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overs_bowled', to='api.player'),
        ),
        migrations.AddField(
            model_name='bowlerscore',
            name='bowler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_scores', to='api.player'),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='batsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_scores', to='api.player'),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wickets_taken_batting', to='api.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='batsman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_faced', to='api.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='bowler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_bowled', to='api.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fielding_dismissals', to='api.player'),
        ),
        migrations.AddField(
            model_name='ball',
            name='non_striker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balls_non_striker', to='api.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='api.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='innings',
            unique_together={('match', 'innings_number')},
        ),
        migrations.AlterUniqueTogether(
            name='over',
            unique_together={('innings', 'over_number')},
        ),
        migrations.AlterUniqueTogether(
            name='bowlerscore',
            unique_together={('innings', 'bowler')},
        ),
        migrations.AlterUniqueTogether(
            name='batsmanscore',
            unique_together={('innings', 'batsman')},
        ),
        migrations.AlterUniqueTogether(
            name='ball',
            unique_together={('over', 'ball_number')},
        ),
    ]
