# Generated by Django 5.2.12 on 2026-05-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cricket_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='batsmanscore',
            name='batting_position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='did_not_bat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='fall_of_wicket_over',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='fall_of_wicket_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batsmanscore',
            name='fielder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches_taken', to='api.player'),
        ),
    ]
