# Generated by Django 5.2.12 on 2026-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_batsman_dismissal_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='youtube_stream_url',
            field=models.URLField(blank=True),
        ),
    ]
