# Generated by Django 5.2.12 on 2026-05-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_cricket_team_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
