# Generated by Django 5.2.12 on 2026-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_player_is_vice_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='admit_card_email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='admit_card_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
