export type AdmitCard = {
  name: string;
  dob: string;
  roll: string;
  class?: string;
  center?: string;
  room?: string;
  reportTime?: string;
  file?: string;
};

export const admitCards: AdmitCard[] = [
  {
    name: "Sample Student",
    dob: "2012-04-15",
    roll: "HBPL0001",
    class: "Class 8",
    center: "Priyam Public School",
    room: "Room 3",
    reportTime: "09:00 AM",
    file: "/admit-cards/HBPL0001.pdf",
  },
  {
    name: "Rahul Sharma",
    dob: "2011-08-20",
    roll: "HBPL0002",
    class: "Class 7",
    center: "City Public School",
    room: "Room 5",
    reportTime: "10:00 AM",
    file: "/admit-cards/HBPL0002.pdf",
  },
  {
    name: "Priya Singh",
    dob: "2010-12-05",
    roll: "HBPL0003",
    class: "Class 9",
    center: "B.M. Memorial School",
    room: "Room 2",
    reportTime: "08:30 AM",
    file: "/admit-cards/HBPL0003.pdf",
  },
  {
    name: "Amit Kumar",
    dob: "2013-03-18",
    roll: "HBPL0004",
    class: "Class 6",
    center: "S.D. Public School",
    room: "Room 4",
    reportTime: "09:30 AM",
    file: "/admit-cards/HBPL0004.pdf",
  },
  {
    name: "Anjali Verma",
    dob: "2011-07-22",
    roll: "HBPL0005",
    class: "Class 8",
    center: "D.M. Memorial Public School",
    room: "Room 1",
    reportTime: "09:00 AM",
    file: "/admit-cards/HBPL0005.pdf",
  },
  {
    name: "Rohit Patel",
    dob: "2012-09-10",
    roll: "HBPL0006",
    class: "Class 7",
    center: "New Central School",
    room: "Room 6",
    reportTime: "10:30 AM",
    file: "/admit-cards/HBPL0006.pdf",
  },
  {
    name: "Kavita Mishra",
    dob: "2010-11-25",
    roll: "HBPL0007",
    class: "Class 10",
    center: "Saraswati Shishu Mandir",
    room: "Room 7",
    reportTime: "08:00 AM",
    file: "/admit-cards/HBPL0007.pdf",
  },
  {
    name: "Vikram Singh",
    dob: "2011-02-14",
    roll: "HBPL0008",
    class: "Class 8",
    center: "Jawahar Navodaya Vidyalaya",
    room: "Room 8",
    reportTime: "09:15 AM",
    file: "/admit-cards/HBPL0008.pdf",
  },
  {
    name: "Neha Gupta",
    dob: "2012-06-30",
    roll: "HBPL0009",
    class: "Class 6",
    center: "Kendriya Vidyalaya",
    room: "Room 9",
    reportTime: "08:45 AM",
    file: "/admit-cards/HBPL0009.pdf",
  },
  {
    name: "Rajesh Kumar",
    dob: "2010-10-08",
    roll: "HBPL0010",
    class: "Class 9",
    center: "Saint Paul's School",
    room: "Room 10",
    reportTime: "10:15 AM",
    file: "/admit-cards/HBPL0010.pdf",
  },
  {
    name: "Pooja Sharma",
    dob: "2013-01-25",
    roll: "HBPL0011",
    class: "Class 5",
    center: "Little Flower School",
    room: "Room 11",
    reportTime: "09:45 AM",
    file: "/admit-cards/HBPL0011.pdf",
  },
  {
    name: "Manoj Kumar",
    dob: "2011-05-12",
    roll: "HBPL0012",
    class: "Class 7",
    center: "Green Valley Public School",
    room: "Room 12",
    reportTime: "08:30 AM",
    file: "/admit-cards/HBPL0012.pdf",
  },
  {
    name: "Sunita Devi",
    dob: "2012-08-03",
    roll: "HBPL0013",
    class: "Class 6",
    center: "Modern Public School",
    room: "Room 13",
    reportTime: "09:30 AM",
    file: "/admit-cards/HBPL0013.pdf",
  },
  {
    name: "Arjun Singh",
    dob: "2010-12-20",
    roll: "HBPL0014",
    class: "Class 10",
    center: "Delhi Public School",
    room: "Room 14",
    reportTime: "08:00 AM",
    file: "/admit-cards/HBPL0014.pdf",
  },
  {
    name: "Meera Kumari",
    dob: "2013-04-18",
    roll: "HBPL0015",
    class: "Class 5",
    center: "Holy Cross School",
    room: "Room 15",
    reportTime: "10:00 AM",
    file: "/admit-cards/HBPL0015.pdf",
  },
  {
    name: "Vivek Kumar",
    dob: "2011-09-05",
    roll: "HBPL0016",
    class: "Class 8",
    center: "Sainik School",
    room: "Room 16",
    reportTime: "09:00 AM",
    file: "/admit-cards/HBPL0016.pdf",
  },
  {
    name: "Anita Singh",
    dob: "2012-02-28",
    roll: "HBPL0017",
    class: "Class 7",
    center: "Mount Carmel School",
    room: "Room 17",
    reportTime: "08:45 AM",
    file: "/admit-cards/HBPL0017.pdf",
  },
  {
    name: "Rakesh Kumar",
    dob: "2010-07-15",
    roll: "HBPL0018",
    class: "Class 9",
    center: "Army Public School",
    room: "Room 18",
    reportTime: "09:15 AM",
    file: "/admit-cards/HBPL0018.pdf",
  },
  {
    name: "Geeta Devi",
    dob: "2013-05-22",
    roll: "HBPL0019",
    class: "Class 6",
    center: "Bal Vikas School",
    room: "Room 19",
    reportTime: "10:30 AM",
    file: "/admit-cards/HBPL0019.pdf",
  },
  {
    name: "Mohan Singh",
    dob: "2011-11-10",
    roll: "HBPL0020",
    class: "Class 8",
    center: "National Public School",
    room: "Room 20",
    reportTime: "08:00 AM",
    file: "/admit-cards/HBPL0020.pdf",
  },
];
