from django.urls import path

from . import api


urlpatterns = [
    path("exam-sessions/", api.PublicSessionListView.as_view(), name="public-exam-sessions"),
    path("schools/", api.PublicSchoolListView.as_view(), name="public-exam-schools"),
    path("exams/", api.PublicExamListView.as_view(), name="public-exams"),
    path("exams/<slug:slug>/", api.PublicExamDetailView.as_view(), name="public-exam-detail"),
    path("auth/register/", api.RegisterView.as_view(), name="exam-register-account"),
    path("auth/verify-email/", api.VerifyEmailView.as_view(), name="exam-verify-email"),
    path("auth/resend-verification/", api.ResendVerificationView.as_view(), name="exam-resend-verification"),
    path("auth/password-reset/", api.StudentPasswordResetRequestView.as_view(), name="exam-password-reset"),
    path("auth/password-reset/confirm/", api.StudentPasswordResetConfirmView.as_view(), name="exam-password-reset-confirm"),
    path("auth/login/", api.LoginView.as_view(), name="exam-login"),
    path("me/", api.MeView.as_view(), name="exam-me"),
    path("eligible-exams/", api.MyEligibleExamListView.as_view(), name="my-eligible-exams"),
    path("applications/", api.MyApplicationListCreateView.as_view(), name="my-applications"),
    path("applications/history/", api.MyApplicationHistoryView.as_view(), name="my-application-history"),
    path("results/", api.MyResultListView.as_view(), name="my-results"),
    path("applications/<int:pk>/", api.MyApplicationDetailView.as_view(), name="my-application-detail"),
    path("applications/<int:pk>/form/", api.MyApplicationFormDownloadView.as_view(), name="my-application-form"),
    path("applications/<int:pk>/submit/", api.SubmitApplicationView.as_view(), name="submit-application"),
    path("applications/<int:pk>/payment-order/", api.CashfreePaymentOrderView.as_view(), name="cashfree-exam-payment-order"),
    path("payments/verify/", api.CashfreePaymentVerifyView.as_view(), name="cashfree-exam-payment-verify"),
    path("cashfree/webhook/", api.CashfreeWebhookView.as_view(), name="exam-cashfree-webhook"),
    path("applications/quick-apply/", api.QuickApplyView.as_view(), name="quick-apply"),
    path("applications/<int:pk>/documents/", api.MyApplicationDocumentView.as_view(), name="application-document"),
    path("staff/exam-sessions/", api.StaffSessionListCreateView.as_view(), name="staff-exam-sessions"),
    path("staff/email-test/", api.StaffEmailTestView.as_view(), name="staff-email-test"),
    path("staff/exam-sessions/<int:pk>/", api.StaffSessionDetailView.as_view(), name="staff-exam-session-detail"),
    path("staff/exams/", api.StaffExamListCreateView.as_view(), name="staff-exams"),
    path("staff/exams/<int:pk>/", api.StaffExamDetailView.as_view(), name="staff-exam-detail"),
    path("staff/exam-centres/", api.StaffExamCentreListCreateView.as_view(), name="staff-exam-centres"),
    path("staff/exam-centres/<int:pk>/", api.StaffExamCentreDetailView.as_view(), name="staff-exam-centre-detail"),
    path("staff/sample-papers/", api.StaffExamSamplePaperListCreateView.as_view(), name="staff-sample-papers"),
    path("staff/sample-papers/<int:pk>/", api.StaffExamSamplePaperDetailView.as_view(), name="staff-sample-paper-detail"),
    path("staff/applications/", api.StaffApplicationListView.as_view(), name="staff-applications"),
    path("staff/payments/", api.StaffCashfreeExamPaymentListView.as_view(), name="staff-exam-payments"),
    path("staff/payments/<int:pk>/accept/", api.StaffAcceptExamPaymentView.as_view(), name="staff-accept-exam-payment"),
    path("staff/applications/auto-assign-centres/", api.StaffAutoAssignCentresView.as_view(), name="staff-auto-assign-centres"),
    path("staff/applications/<int:pk>/", api.StaffApplicationDetailView.as_view(), name="staff-application-detail"),
    path("staff/applications/<int:pk>/transition/", api.StaffApplicationTransitionView.as_view(), name="staff-application-transition"),
    path("staff/exam-results/", api.StaffExamResultListCreateView.as_view(), name="staff-exam-results"),
    path("staff/exam-results/<int:pk>/", api.StaffExamResultDetailView.as_view(), name="staff-exam-result-detail"),
]
