# Generated by Django 5.2.12 on 2026-05-15 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0023_cricket_team_structure'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Exam Categories',
                'db_table': 'exams_exam_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('participation', 'Participation'), ('merit', 'Merit'), ('topper', 'Topper'), ('scholarship', 'Scholarship')], max_length=20)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.examregistration')),
            ],
            options={
                'db_table': 'exams_certificate',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='exams.certificate')),
            ],
            options={
                'db_table': 'exams_certificate_verification',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('academic_year', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('admit_card_out', 'Admit Card Out'), ('ongoing', 'Ongoing'), ('result_pending', 'Result Pending'), ('result_out', 'Result Out'), ('completed', 'Completed')], default='upcoming', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_registrations', models.PositiveIntegerField(blank=True, null=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brochure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_brochures', to='core.mediaasset')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='exams.examcategory')),
            ],
            options={
                'db_table': 'exams_exam',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='exams.exam'),
        ),
        migrations.CreateModel(
            name='AdmitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=50)),
                ('hall_ticket_number', models.CharField(blank=True, max_length=100)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('generated', 'Generated'), ('downloaded', 'Downloaded'), ('invalidated', 'Invalidated')], default='generated', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('exam_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.examcenterdetail')),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admit_card', to='api.examregistration')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admit_cards', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_admit_card',
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('obtained_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('is_pass', models.BooleanField(blank=True, null=True)),
                ('copy_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_uploaded', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('copy_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='api.examregistration')),
            ],
            options={
                'db_table': 'exams_exam_result',
                'ordering': ['rank', '-obtained_marks'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('is_tentative', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='exams.exam')),
            ],
            options={
                'db_table': 'exams_exam_timeline',
                'ordering': ['event_date', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RankHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('achievement', models.CharField(blank=True, max_length=300)),
                ('is_featured', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_holders', to='exams.exam')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('registration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.examregistration')),
            ],
            options={
                'db_table': 'exams_rank_holder',
                'ordering': ['exam', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='ResultPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='exams.exam')),
                ('result_pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
            ],
            options={
                'db_table': 'exams_result_publication',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_pass', models.BooleanField(default=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_breakdown', to='exams.examresult')),
            ],
            options={
                'db_table': 'exams_score_breakdown',
                'ordering': ['subject'],
            },
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_number'], name='exams_certi_certifi_64e2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='admitcard',
            index=models.Index(fields=['roll_number'], name='exams_admit_roll_nu_4daaf1_idx'),
        ),
        migrations.AddIndex(
            model_name='admitcard',
            index=models.Index(fields=['hall_ticket_number'], name='exams_admit_hall_ti_ef20c1_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['slug'], name='exams_exam_slug_b55380_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exams_exam_status_7a27f8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['academic_year'], name='exams_exam_academi_a219af_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['exam', 'rank'], name='exams_exam__exam_id_f82634_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['copy_status'], name='exams_exam__copy_st_fc2add_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['roll_number'], name='exams_exam__roll_nu_edbc50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rankholder',
            unique_together={('exam', 'rank')},
        ),
    ]
