# Generated by Django 5.2.12 on 2026-09-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examinationsession_school_exam_application_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='admit_card_template',
            field=models.FileField(blank=True, null=True, upload_to='exam/templates/admit-cards/'),
        ),
        migrations.AddField(
            model_name='exam',
            name='certificate_template',
            field=models.FileField(blank=True, null=True, upload_to='exam/templates/certificates/'),
        ),
    ]
