# Generated by Django 5.2.12 on 2026-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_allowed_classes_examresult_application_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examapplication',
            name='admit_card_email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='admit_card_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
