# Generated by Django 5.2.12 on 2026-09-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examapplication_admit_card_email_last_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Available student seats')),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('facilities', models.TextField(blank=True, help_text='Facilities and accessibility notes')),
                ('internal_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam centre',
                'verbose_name_plural': 'Exam centres',
                'db_table': 'exams_exam_centre',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='centres',
            field=models.ManyToManyField(blank=True, related_name='exams', to='exams.examcentre'),
        ),
    ]
