# Generated by Django 5.2.12 on 2026-09-29 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examcentre_exam_centres'),
    ]

    operations = [
        migrations.AddField(
            model_name='examapplication',
            name='admit_card_file',
            field=models.FileField(blank=True, null=True, upload_to='exam/admit-cards/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='admit_card_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='exams.examcentre'),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='certificate_email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='certificate_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='exam/certificates/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='certificate_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
