# Generated by Django 5.2.12 on 2026-10-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_examregistration_admit_card_email_last_error_and_more'),
        ('core', '0002_emailserviceconfiguration'),
        ('exams', '0008_use_session_for_exam_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdmitCard',
            new_name='LegacyAdmitCard',
        ),
        migrations.AlterModelOptions(
            name='legacyadmitcard',
            options={'verbose_name': 'Legacy admit card', 'verbose_name_plural': 'Legacy admit cards'},
        ),
    ]
