# Generated by Django 5.2.12 on 2026-10-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_rename_admitcard_legacyadmitcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examapplication',
            name='application_confirmation_email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='examapplication',
            name='application_confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
