# Generated by Django 5.2.12 on 2026-10-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_allow_registration_results_per_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashfreeExamPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=45, unique=True)),
                ('payment_session_id', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('user_dropped', 'User dropped'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('cf_payment_id', models.CharField(blank=True, max_length=40)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashfree_payments', to='exams.examapplication')),
            ],
            options={
                'db_table': 'exams_cashfree_exam_payment',
                'ordering': ['-created_at'],
            },
        ),
    ]
