# Generated by Django 5.2.12 on 2026-10-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0015_cashfreeexampayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfreeexampayment',
            name='payment_confirmation_email_last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cashfreeexampayment',
            name='payment_confirmation_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
