# Generated by Django 5.2.12 on 2026-10-04 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_cashfreeexampayment_payment_confirmation_email_last_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashfreeexampayment',
            name='manual_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cashfreeexampayment',
            name='manually_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashfreeexampayment',
            name='manually_accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manually_accepted_exam_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashfreeexampayment',
            name='payment_method',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('manual', 'Manual')], default='cashfree', max_length=20),
        ),
    ]
