# Generated by Django 5.2.12 on 2026-10-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_cashfreeexampayment_manual_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashfreeexampayment',
            name='payment_method',
            field=models.CharField(choices=[('cashfree', 'Cashfree'), ('manual', 'Manual'), ('no_charge', 'No charge')], default='cashfree', max_length=20),
        ),
        migrations.AlterField(
            model_name='cashfreeexampayment',
            name='payment_session_id',
            field=models.TextField(blank=True),
        ),
    ]
