# Generated by Django 5.2.12 on 2026-10-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0018_alter_cashfreeexampayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='admit_card_template',
            field=models.FileField(blank=True, help_text='PDF or Django-rendered HTML/HTM. HTML tokens: {{ student_name }}, {{ application_number }}, {{ student_class }}, {{ student_dob }}, {{ school_name }}, {{ exam_name }}, {{ exam_date }}, {{ reporting_time }}, {{ exam_time }}, {{ centre_name }}, {{ centre_address }}, {{ student_photo_data_uri }}, {{ student_signature_data_uri }}.', null=True, upload_to='exam/templates/admit-cards/'),
        ),
    ]
