# Generated by Django 5.2.12 on 2026-10-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_alter_exam_admit_card_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='certificate_template',
            field=models.FileField(blank=True, help_text='PDF or Django-rendered HTML/HTM. HTML tokens: {{ student_name }}, {{ student_class }}, {{ position_rank }}, {{ exam_name }}, {{ exam_session }}, {{ certificate_number }}, {{ issue_date }}.', null=True, upload_to='exam/templates/certificates/'),
        ),
    ]
