# Generated by Django 5.2.12 on 2026-10-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0021_studentprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="exams.examinationsession",
            ),
        ),
        migrations.AlterField(
            model_name="examapplication",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="examapplication",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="exams.studentprofile",
            ),
        ),
    ]
