# Generated by Django 5.2.12 on 2026-10-06

from django.db import migrations, models


def move_existing_publication_state(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    Application = apps.get_model("exams", "ExamApplication")
    card_statuses = ["admit_card_out", "ongoing", "result_pending", "result_out", "completed"]
    result_statuses = ["result_out", "completed"]
    Application.objects.filter(exam__status__in=card_statuses).update(admit_card_published=True)
    Application.objects.filter(exam__status__in=result_statuses).update(results_published=True)
    Exam.objects.filter(status__in=["admit_card_out", "result_pending", "result_out"]).update(status="registration_closed")


class Migration(migrations.Migration):
    dependencies = [("exams", "0022_allow_exam_data_cascade_deletion")]

    operations = [
        migrations.AddField(
            model_name="examapplication",
            name="admit_card_published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examapplication",
            name="results_published",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(move_existing_publication_state, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="exam",
            name="status",
            field=models.CharField(choices=[("upcoming", "Upcoming"), ("registration_open", "Registration Open"), ("registration_closed", "Registration Closed"), ("ongoing", "Ongoing"), ("completed", "Completed")], default="upcoming", max_length=30),
        ),
    ]
