# Generated by Django 5.2.12 on 2026-05-17 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTournamentStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matches_played', models.PositiveSmallIntegerField(default=0)),
                ('innings_batted', models.PositiveSmallIntegerField(default=0)),
                ('not_outs', models.PositiveSmallIntegerField(default=0)),
                ('runs', models.PositiveIntegerField(default=0)),
                ('highest_score', models.PositiveSmallIntegerField(default=0)),
                ('balls_faced', models.PositiveIntegerField(default=0)),
                ('fours', models.PositiveSmallIntegerField(default=0)),
                ('sixes', models.PositiveSmallIntegerField(default=0)),
                ('fifties', models.PositiveSmallIntegerField(default=0)),
                ('hundreds', models.PositiveSmallIntegerField(default=0)),
                ('innings_bowled', models.PositiveSmallIntegerField(default=0)),
                ('balls_bowled', models.PositiveIntegerField(default=0)),
                ('runs_given', models.PositiveIntegerField(default=0)),
                ('wickets', models.PositiveSmallIntegerField(default=0)),
                ('best_wickets', models.PositiveSmallIntegerField(default=0)),
                ('best_runs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maidens', models.PositiveSmallIntegerField(default=0)),
                ('catches', models.PositiveSmallIntegerField(default=0)),
                ('run_outs', models.PositiveSmallIntegerField(default=0)),
                ('stumpings', models.PositiveSmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stats', to='cricket.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='cricket.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='cricket.tournament')),
            ],
            options={
                'unique_together': {('player', 'tournament')},
            },
        ),
    ]
