# Generated by Django 5.2.12 on 2026-05-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_playertournamentstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='striker_slot',
            field=models.SmallIntegerField(default=0),
        ),
    ]
